application: newsai-1166
version: 1
runtime: go
api_version: go1
module: default
instance_class: F2

handlers:
- url: /tasks/removeExpiredSessions
  script: _go_app
  login: admin
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png
- url: /.*
  script: _go_app
  secure: always

automatic_scaling:
  min_idle_instances: 2

env_variables:
